# Generated by Django 5.1.4 on 2025-03-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_scores"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Scores",
        ),
    ]
