# Generated by Django 5.1.4 on 2025-03-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scores",
            name="remarks",
        ),
    ]
