# Generated by Django 5.1.4 on 2025-03-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_scores_remarks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Scores",
        ),
    ]
