# Generated by Django 5.1.4 on 2025-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_publication_likes_comment_saved"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="slug",
            field=models.SlugField(blank=True, default="", editable=False, unique=True),
        ),
    ]
