# Generated by Django 5.1.4 on 2025-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_publication_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
