# Generated by Django 5.1.4 on 2025-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_comment_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="publication_id",
            field=models.IntegerField(),
        ),
    ]
