# Generated by Django 5.1.4 on 2025-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_comment_publication_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="publication_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="likes",
            name="user_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="saved",
            name="publication_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="saved",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
