# Generated by Django 5.1.4 on 2025-03-09 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_news"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="Description",
            new_name="text",
        ),
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 3, 9, 13, 25, 27, 353425, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
